### ISSUE TITLE
Building on Linux

### ISSUE THREAD

**Issue by asvc** [cryham/ccc#4]
There seems to be several places in code that are MS Windows-specific. I have added missing declarations, just to check if an application can be built at all.

Please see lines with comments below:

App_Init.cpp:109
```cpp
bool App::StartExe()
    bool er = int(ShellExecute(NULL, "open", s.c_str(), NULL, NULL, SW_SHOWDEFAULT)) <= 32;
#else
        system(s.c_str()); 
        bool er = false;  // Probably wrong, leaving for now
#endif
    status.Set(er ? "Start "+sDC+" error!" : "Started "+sDC+".", er ? 0.1f : 0.62f);
        status.Set(er ? "Start "+sDC+" error!" : "Started "+sDC+".", er ? 0.1f : 0.62f);
    return er;
}
```

Settings.cpp:66
```cpp
void Settings::Default()
    strcpy(pathTCexe, "c:\\Program Files\\Total Commander\\totalcmd.exe");
#else
    char pathDC[256];  // Probably wrong, leaving for now
    strcpy(pathDC, "");
    strcpy(pathDCexe, "doublecmd");
#endif
```

And, as discussed in #2,  App_Graph.cpp:3
```cpp
#include "App.h"
#include "Util.h"
#include <math.h> // Added per https://github.com/cryham/ccc/issues/2
using namespace std;
```

Now application compiles, but linking fails as it seems to rely on Windows-specififc libraries (?). I have found some packaged with Wine, however `ldd` skips them as incompatible:
```make
$ make
[  4%] Linking CXX executable ccc
/usr/bin/ld: cannot find -lopengl32
/usr/bin/ld: cannot find -lglu32
/usr/bin/ld: cannot find -lgdi32
collect2: error: ld returned 1 exit status
CMakeFiles/ccc.dir/build.make:371: recipe for target 'ccc' failed
make[2]: *** [ccc] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/ccc.dir/all' failed
make[1]: *** [CMakeFiles/ccc.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

I am happy to collate all changes necessary into a pull request once linking is sorted.

**Comment by cryham** [comment]
Right. Thanks for testing. I still don't have a working Linux VM to test.
I pushed fixes to master (for those issues above).
I'm not sure how to start DC from command line on (any) Linux (for pathDCexe) is just "doublecmd" okay?

**Comment by asvc** [comment]
Almost. There is a bundled .sh script, however personally I use this:

```bash
cd /path/to/the/doublecmd
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)
./doublecmd
```

**Comment by asvc** [comment]
Pulled latest changes, current state of linking:
```make
[100%] Linking CXX executable ccc
/usr/bin/ld: CMakeFiles/ccc.dir/libs/imgui-SFML.cpp.o: undefined reference to symbol 'glEnable'
//usr/lib/x86_64-linux-gnu/libGL.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/ccc.dir/build.make:371: recipe for target 'ccc' failed
make[2]: *** [ccc] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/ccc.dir/all' failed
make[1]: *** [CMakeFiles/ccc.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by cryham** [comment]
Well I can't really fix or test it myself.
2nd line looks like linker is missing libGL, next is an error I looked on internet and seems a common issue:
https://stackoverflow.com/questions/23729213/link-error-when-trying-to-build-a-simple-opengl-program/23729506#23729506
You could try adding:
`target_link_libraries(${PROJECT} "-lGL")`
But IDK where, either before the line with `${SFML_LIBRARIES})` or at end. 
There is some info here about SFML
https://en.sfml-dev.org/forums/index.php?topic=24070.0
I only quickly looked at it, and seems to me that SFML should now handle GL libs too without adding. But then this happens with imgui-SFML, maybe there is something different. Just guessing.

**Comment by cryham** [comment]
Okay I'm on Debian 10 now and I fixed few things in CCC.
It should build fine now on Linux and work with doublecmd. :+1:

**Comment by asvc** [comment]
Thanks so much for taking care of it! Your default colours are bad-ass, do you plan to release "light" version of the colour-scheme?

**Comment by cryham** [comment]
Thanks.
Right now no, not really.
I think it'd be probably better to move from R,G,B to H,S,V and them make some global option to inverse colors (V brightness, maybe with some contrast option too), this would be way less manual work.

**Comment by asvc** [comment]
Just one note, you might want to consider inverting "L" in HSL instead of "V" in HSV... Or add both options :)

Thanks!
